### ISSUE TITLE
Unable to create process using '/bin/python3 steamwintersale.py ' ?

### ISSUE THREAD

**Issue by thisVioletHydra** [sffxzzp/steamwintersale18#1]
λ py steamwintersale.py
Unable to create process using '/bin/python3 steamwintersale.py '

```
λ py
Python 3.7.2rc1 (tags/v3.7.2rc1:75a402a217, Dec 11 2018, 23:05:39) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by thisVioletHydra** [comment]
```
λ python steamwintersale.py
12/24-14:26:59|12820|ERROR|Bot: |LoadConfig|Error
12/24-14:26:59|13320|ERROR|Bot: mybotidiot1|LoadConfig|Error
12/24-14:26:59|12820|INFO|Bot: |CheckDoors|CheckCookies
12/24-14:26:59|13320|INFO|Bot: mybotidiot1|CheckDoors|CheckCookies
12/24-14:26:59|12820|DEBUG|Starting new HTTPS connection (1): store.steampowered.com:443
12/24-14:26:59|13320|DEBUG|Starting new HTTPS connection (1): store.steampowered.com:443
12/24-14:27:00|12820|DEBUG|https://store.steampowered.com:443 "GET /promotion/cottage_2018/ HTTP/1.1" 200 7930
12/24-14:27:00|12820|WARNING|Bot: |CheckDoors|AccountNotLogin
12/24-14:27:00|12820|INFO|Bot: |ThreadSleep|1 hour
12/24-14:27:00|13320|DEBUG|https://store.steampowered.com:443 "GET /promotion/cottage_2018/ HTTP/1.1" 200 9971
12/24-14:27:00|13320|INFO|Bot: mybotidiot1|CheckDoors|Checking...
12/24-14:27:00|13320|INFO|Bot: mybotidiot1|CheckDoors|NewDoorFound
```

config correct i twice recheck it

**Comment by sffxzzp** [comment]
@mrG0bliN 
This script uses `Pool` in `multiprocessing.dummy`, and this may cause some error. Try remove the `.dummy` may fix this problem. But this script worked fine on my machine.

Sorry for the inconvinence that I didn't exclude `.gitignore` file, delete it.

And the last, the config file which only has cookies inside is actually in one line.
with the format looks like the line below.
`ABCDE=12345; BCDEF=23456; CDEFG=34567`

Actually, If you follow the steps which I wrote in README.md, the raw cookies copied from DevTool could directly pasted in the config file you've created.

OH. AND THE MOST INPORTANT IS, The cookies would expire, and I'm still working on it.

**Comment by thisVioletHydra** [comment]
@sffxzzp 
Dr. Mate i have a bugs 🐞  
1. if i add `;` in end line my config files -> script throw `error`.
2. After paste `Cookie` in file, i need TWICE run script to correct work.
3. Why `py` not work? Only `python` worked =\

**Comment by sffxzzp** [comment]
@mrG0bliN 
No, you don't need to add `;` at the end of line but middle of the line to split the parts, because the raw that copied directly from browser is in this format.

Run this script again after you change the config file isn't that annoying. But it is annoying if you don't understand the steps to fetch the raw cookies, cuz you need to restart it over and over again to ensure it works.

I don't know why `py` don't work, but if `python` works on your device, you could just use it instead of using `py`.
