### ISSUE TITLE
multiacc? 

### ISSUE THREAD

**Issue by thisVioletHydra** [sffxzzp/steamwintersale18#3]
![image](https://user-images.githubusercontent.com/11839238/50470764-f5950400-09c2-11e9-80a9-7c8e75056072.png)

**Comment by sffxzzp** [comment]
@mrG0bliN 
What's your point? I have 3 accounts and it all works well.
If you are experiencing `AccountNotLogin` problem, try login with `Remember me on this computer` options checked, and then get cookies that has **steamRememberLogin**.

**Comment by thisVioletHydra** [comment]
> @mrG0bliN
> What's your point? I have 3 accounts and it all works well.
> If you are experiencing `AccountNotLogin` problem, try login with `Remember me on this computer` options checked, and then get cookies that has **steamRememberLogin**.

after swith account  i lost last accestp poin :c

**Comment by sffxzzp** [comment]
@mrG0bliN
Can't understand what you said.
But if you want to get another account's cookies, **CLEAR IT** in DevTools instead of logout.
